language: csharp
solution: Pips.NET.sln
mono: none
dotnet: 2.0.0
script:
    - dotnet restore
    - dotnet build -c Release
    - ls `pwd`/*.Test/*.csproj | xargs -L1 dotnet test -c Release
notifications:
    email: false