sudo: required
services:
  - docker
env:
  global:
    - CI_IMAGE=pips-net:ci
    - BASE_IMAGE=rehret/pips-net
script:
  - docker build -t $CI_IMAGE -f Pips/Dockerfile .
after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" <> "false" ]; then echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin; docker tag $CI_IMAGE rehret/pips-net:pr-${TRAVIS_PULL_REQUEST}; docker push rehret/pips-net:pr-${TRAVIS_PULL_REQUEST}; fi
  - if [ -n "$TRAVIS_TAG" ]; then echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin; docker tag $CI_IMAGE rehret/pips-net:${TRAVIS_TAG}; docker push rehret/pips-net:${TRAVIS_TAG}; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin; docker tag $CI_IMAGE rehret/pips-net:latest; docker push rehret/pips-net:latest; fi
script: echo ""
notifications:
  email: false